### PR TITLE
Fix padding to 40px.

### PR DESCRIPTION
**Pull request by akatsoulas**
@Juriv could you do a quick review on this please?

### CODE REVIEW

**Comment by Juriv** [comment]
yes, it's fine, could you add this code to `padding: 10px 20px 40px;` 268 line

**Comment by akatsoulas** [comment]
@Juriv are you referring to the media selector? If I add this line there, it breaks the design. Can you please verify this?

**Comment by akatsoulas** [comment]
I am merging this in order to fix the misalignment. @Juriv if there is something missing, could you please open a new PR. Thanks!

**Comment by vladsov** [comment]
@akatsoulas 
screenshot 2019-02-20 16 29 01

**Comment by akatsoulas** [comment]
Addressed here
https://github.com/mozilla/sumo-experiments/pull/48/commits/1ce75cc8c7e0cc53f7b536cae9c4fcd69c911eba

**Pull request merged**
