### PR TITLE
updated styles

### PR DESCRIPTION
**Pull request by Juriv**

### CODE REVIEW

**Comment by akatsoulas** [comment]
Hi @kiberken @Juriv. Is this PR ready to be merged or are you still working on it?

**Comment by Juriv** [comment]
@akatsoulas yes, you could merge. However since you slightly changed the structure of html, our changes will not merge smoothly to your code. We restored back our original index.html and index-b.html pages so you could use them as a reference during the merging.
Live version could be found there:
https://ramotion.github.io/sumo-experiments/index.html
https://ramotion.github.io/sumo-experiments/index-b.html

**Comment by akatsoulas** [comment]
@Juriv it seems that some of the changes made it through and are added into those templates. Could you please drop those changes from this PR and keep only the reference `index.html` and `index-b.html`?

**Comment by Juriv** [comment]
@akatsoulas i'll check what we can do

**Comment by Juriv** [comment]
@akatsoulas could you check now

**Review by akatsoulas — APPROVED** [review]

**Pull request merged**
